### ISSUE TITLE
MaxHZ amplitude

### ISSUE THREAD

**Issue by Greg767** [krafter/DetectingAudioFrequency#1]
Hi,

Could you please help me how to find the input sound level in your computeFFT method? Everything is working fine, but I'd like to know when the system starts to analyze user created sound and not just noise.
Thanks

UPDATE:
Fortunately I could manage this. So I created a method in FFTHelper.mm:

float computeLevel(FFTHelperRef *fftHelperRef, long numSamples)
{
    float meanVal = 0;
    float one = 1.0;
    vDSP_vsq(fftHelperRef->complexA.realp, 1, fftHelperRef->complexA.realp, 1, numSamples/2);
    vDSP_meanv(fftHelperRef->complexA.realp, 1, &meanVal, numSamples/2);
    vDSP_vdbcon(&meanVal, 1, &one, &meanVal, 1, 1, 0);
    return meanVal;
}

**Comment by jamrader** [comment]
If I'm not mistaking you only sample the audio input about every 3 seconds for the max Hz. Is there a way I can increase this? Say to sampling the incoming audio for the max Hz fifteen times a second?
