### ISSUE TITLE
How i can use this Code in swift ??

### ISSUE THREAD

**Issue by Arun30sep** [krafter/DetectingAudioFrequency#5]
I need top two frequencies within 3 second and time between them. I really don't undertstand whats going on in the after initialising the moaudio in Viewcontroller. Just started with fft so not a complete knowledge of the concepts.

**Comment by jagdeep90** [comment]
How i can use this Code in swift too ??

**Comment by krafter** [comment]
@Arun30sep  3 seconds = yourSampleRate*3. See the C++ functions above ViewController class - all the stuff happens in there. It starts in AudioCallback(). 
@jagdeep90 you can use Objective-C++ code in swift project, just not in the same file.
